file = open("introduction.txt", "w")
file.write("Hello!\n")
file.write("My name is Vaishnavi.\n")
file.write("I am studying Computer Science Engineering.\n")
file.write("I am learning Python for Data Analytics.")
file.close()
file = open("introduction.txt", "r")
content = file.read()
print(content)
file.close()